"""Centralised backend configuration (read from environment / .env)."""
from functools import lru_cache
from pathlib import Path

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # MongoDB
    MONGO_URI: str = "mongodb://localhost:27017"
    DB_NAME: str = "hospital_susana_lopez"
    # Optional URI of a MongoDB user that ONLY has the built-in `read` role. When set, every
    # query generated by the AI agent runs through it (server-side read-only enforcement).
    MONGO_READONLY_URI: str = ""

    # OpenAI (empty key => the agent runs in fallback "Plan B" mode)
    OPENAI_API_KEY: str = ""
    OPENAI_MODEL: str = "gpt-4o"
    OPENAI_TIMEOUT_SECONDS: float = 30.0

    # Security
    JWT_SECRET: str = "change-me-with-a-long-random-string"
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRE_MINUTES: int = 480
    CORS_ORIGINS: str = "http://localhost:8501"
    BOOTSTRAP_ADMIN_EMAIL: str = "admin@hospital.local"
    BOOTSTRAP_ADMIN_PASSWORD: str = ""
    BOOTSTRAP_ADMIN_NAME: str = "Administrator"

    # Data loading
    DATA_DIR: str = "app/data"
    EXCEL_FILENAME: str = "DateBaseHIS.xlsx"
    MAX_UPLOAD_MB: int = 120
    # Real bed capacity per bed group (JSON). Overrides the "distinct beds observed" proxy,
    # e.g. {"UNIDAD DE CUIDADO INTENSIVO": 12, "PEDIATRIA": 40}
    BED_CAPACITY_OVERRIDES: str = ""
    QUERY_MAX_TIME_MS: int = 8000

    # Agent
    CHAT_MEMORY_TURNS: int = 6
    DEFAULT_LANGUAGE: str = "es"
    CHAT_MAX_ANSWER_TOKENS: int = 450

    # In-memory caches (seconds). Dataset-derived values are also keyed by the ETL run id,
    # so they are never stale after a new load; the TTL only bounds memory.
    CACHE_TTL_SECONDS: int = 3600
    CHAT_CACHE_TTL_SECONDS: int = 900
    METADATA_CACHE_TTL_SECONDS: float = 5.0

    # Billing module (optional, admin-only). Tariffs are JSON: unit price per CUPS / medication
    # code plus a "default", e.g. {"services": {"default": 0, "890201": 35000}, "medications": {"default": 0}}
    BILLING_ENABLED: bool = True
    BILLING_CURRENCY: str = "COP"
    BILLING_TARIFFS: str = ""

    # Alerts / n8n
    N8N_WEBHOOK_URL: str = ""
    N8N_WEBHOOK_SECRET: str = ""
    # Dry run: build the payloads but do not send them; report a simulated success.
    # The test suite enables it (tests/conftest.py); use it for demos without n8n.
    N8N_DRY_RUN: bool = False
    ALERT_LANGUAGE: str = "es"
    ALERT_CHECK_INTERVAL_SECONDS: int = 900
    ALERT_OCCUPANCY_THRESHOLD_PCT: float = 85.0
    ALERT_INVENTORY_DAYS_THRESHOLD: float = 5.0
    ALERT_ER_WAIT_THRESHOLD_MIN: float = 60.0
    ALERT_TRIAGE2_WAIT_THRESHOLD_MIN: float = 30.0
    ALERT_SURGERY_COMPLETION_THRESHOLD_PCT: float = 70.0

    # Request shield (app/core/shield.py)
    API_MAX_JSON_BYTES: int = 64 * 1024
    RATE_LIMIT_ENABLED: bool = True
    RATE_LIMIT_PER_MIN: int = 300
    RATE_LIMIT_AGENT_PER_MIN: int = 30
    RATE_LIMIT_LOGIN_PER_MIN: int = 20
    RATE_LIMIT_WRITE_PER_MIN: int = 60

    # n8n AI agent integration: shared secret sent by n8n in `X-Integration-Key`.
    # Empty = the /api/integrations endpoints are disabled. At least 32 characters.
    INTEGRATION_API_KEY: str = ""

    # SQL Server (hospital system of record). Empty host = "mongo_only" mode: records inserted
    # from the app go only to MongoDB (ids from a separate range, see records_service).
    SQLSERVER_HOST: str = ""
    SQLSERVER_PORT: int = 1433
    SQLSERVER_DATABASE: str = "HIS"
    SQLSERVER_USER: str = ""
    SQLSERVER_PASSWORD: str = ""
    SQLSERVER_SCHEMA: str = "dbo"
    SQLSERVER_TIMEOUT_SECONDS: int = 15

    # Records inserted from the app
    HOSPITAL_TIMEZONE: str = "America/Bogota"
    RECORDS_MAX_BACKDATE_DAYS: int = 30
    SYNC_RETRY_INTERVAL_SECONDS: int = 120

    LOG_LEVEL: str = "INFO"

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    @field_validator("DEFAULT_LANGUAGE", "ALERT_LANGUAGE")
    @classmethod
    def _supported_language(cls, value: str) -> str:
        return value if value in ("es", "en") else "es"

    @property
    def cors_origins(self) -> list[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",") if o.strip() and o.strip() != "*"]

    @property
    def excel_path(self) -> Path:
        """The ONLY file the ETL is allowed to read. Clients can never choose a path."""
        return Path(self.DATA_DIR) / self.EXCEL_FILENAME

    @property
    def bed_capacity_overrides(self) -> dict[str, int]:
        import json

        try:
            data = json.loads(self.BED_CAPACITY_OVERRIDES) if self.BED_CAPACITY_OVERRIDES.strip() else {}
            return {str(k): int(v) for k, v in data.items() if int(v) > 0}
        except (ValueError, TypeError, AttributeError):
            return {}

    @property
    def billing_tariffs(self) -> dict[str, dict[str, float]]:
        import json

        try:
            data = json.loads(self.BILLING_TARIFFS) if self.BILLING_TARIFFS.strip() else {}
            return {
                kind: {str(code): float(price) for code, price in (data.get(kind) or {}).items() if float(price) >= 0}
                for kind in ("services", "medications")
            }
        except (ValueError, TypeError, AttributeError):
            return {"services": {}, "medications": {}}

    @field_validator("SQLSERVER_SCHEMA")
    @classmethod
    def _safe_identifier(cls, value: str) -> str:
        """The schema is interpolated into SQL identifiers: only [A-Za-z0-9_] is accepted."""
        import re

        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,63}", value):
            raise ValueError("SQLSERVER_SCHEMA must be a plain identifier")
        return value

    @property
    def sqlserver_enabled(self) -> bool:
        return bool(self.SQLSERVER_HOST.strip())

    @property
    def integration_enabled(self) -> bool:
        return len(self.INTEGRATION_API_KEY.strip()) >= 32

    @property
    def openai_enabled(self) -> bool:
        return bool(self.OPENAI_API_KEY.strip())

    @property
    def insecure_jwt_secret(self) -> bool:
        return self.JWT_SECRET.startswith("change-me") or len(self.JWT_SECRET) < 32


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()

# Collection names in one place (English, snake_case).
COLLECTIONS = {
    "admissions": "admissions",
    "inventory": "inventory",
    "medication_usage_daily": "medication_usage_daily",
    "service_demand_daily": "service_demand_daily",
    "bed_capacity": "bed_capacity",
    "metadata": "metadata",
    "users": "users",
    "alerts": "alerts",
    "alert_history": "alert_history",
    "alert_events": "alert_events",
    "counters": "counters",
    "sync_outbox": "sync_outbox",
    "conversations": "conversations",
    "agent_logs": "agent_logs",
}

# The ONLY collections the AI agent can read (through app.db.readonly). Users, alerts,
# conversations and logs are never reachable from a generated query.
AGENT_READABLE_COLLECTIONS = frozenset({
    COLLECTIONS["admissions"], COLLECTIONS["inventory"], COLLECTIONS["medication_usage_daily"],
    COLLECTIONS["service_demand_daily"], COLLECTIONS["bed_capacity"],
})

# Fields that must never leave the backend (PII / specific diagnosis).
PII_PATHS = (
    "patient.name",
    "patient.birth_date",
    "patient.patient_id",
    "triage.chief_complaint",
    "diagnosis.code",
    "diagnosis.name",
)
