"""Server-side message catalogue (Spanish / English).

Used for texts generated by the backend itself: alert messages sent to Telegram,
Plan B (no-LLM) answers and the conclusions of the inferential reports.
"""
from typing import Any

SUPPORTED_LANGUAGES = ("es", "en")
LANGUAGE_NAMES = {"es": "Spanish (Colombia)", "en": "English"}

MESSAGES: dict[str, dict[str, str]] = {
    # ---------- Generic ----------
    "fallback_note": {
        "es": "_(Respuesta en modo de contingencia: consulta predefinida, sin IA externa.)_",
        "en": "_(Contingency mode answer: predefined query, no external AI.)_",
    },
    "no_match": {
        "es": "No reconocí la pregunta en el modo de contingencia. Prueba con: ocupación de UCI, "
              "medicamentos con pocos días de inventario, espera en urgencias, servicio con más ingresos, "
              "cirugías realizadas vs. programadas, espera por triage o demanda por especialidad.",
        "en": "I could not recognise the question in contingency mode. Try: ICU occupancy, medications with "
              "few days of inventory, ER waiting time, service with most admissions, surgeries performed vs. "
              "scheduled, waiting time by triage or demand by specialty.",
    },
    "no_data": {"es": "La consulta no devolvió resultados.", "en": "The query returned no results."},
    "agent_error": {
        "es": "No pude responder esa pregunta con los datos disponibles. Intenta reformularla.",
        "en": "I could not answer that question with the available data. Try rephrasing it.",
    },
    "out_of_scope": {
        "es": "Esa pregunta está fuera del alcance de los datos operativos del hospital.",
        "en": "That question is outside the scope of the hospital's operational data.",
    },
    # ---------- Plan B answers ----------
    "fb_occupancy_group": {
        "es": "Al {date}, {group} tiene {occupied} camas ocupadas de {beds} ({pct}% de ocupación estimada).",
        "en": "As of {date}, {group} has {occupied} occupied beds out of {beds} ({pct}% estimated occupancy).",
    },
    "fb_occupancy_all": {
        "es": "Ocupación estimada al {date}:\n{lines}",
        "en": "Estimated occupancy as of {date}:\n{lines}",
    },
    "fb_low_inventory": {
        "es": "{count} medicamentos/insumos tienen menos de {days} días de inventario. Los más críticos:\n{lines}\n"
              "_Nota: el stock es simulado (el HIS no trae inventario); el consumo diario es real._",
        "en": "{count} medications/supplies have less than {days} days of inventory. Most critical:\n{lines}\n"
              "_Note: stock is simulated (the HIS has no inventory table); daily consumption is real._",
    },
    "fb_low_inventory_none": {
        "es": "Ningún medicamento tiene menos de {days} días de inventario.",
        "en": "No medication has less than {days} days of inventory.",
    },
    "fb_er_wait": {
        "es": "Entre el {start} y el {end}, la espera promedio en urgencias (ingreso → atención) fue de "
              "{mean} minutos en {count} pacientes.",
        "en": "Between {start} and {end}, the average ER wait (admission → attention) was {mean} minutes "
              "across {count} patients.",
    },
    "fb_top_service": {
        "es": "En el periodo {period}, el servicio con más pacientes ingresados es {group} con {count} ingresos. "
              "Le siguen: {others}.",
        "en": "In the period {period}, the service with the most admitted patients is {group} with {count} admissions. "
              "Next: {others}.",
    },
    "unit_days": {"es": "días", "en": "days"},
    "fb_top_meds": {"es": "Medicamentos de mayor consumo ({period}):\n{lines}",
                    "en": "Most consumed medications ({period}):\n{lines}"},
    "fb_least_meds": {"es": "Medicamentos de menor rotación ({period}):\n{lines}",
                      "en": "Lowest-turnover medications ({period}):\n{lines}"},
    "fb_surgeries": {
        "es": "Se programaron {scheduled} procedimientos quirúrgicos y se realizaron {performed} ({pct}%).",
        "en": "{scheduled} surgical procedures were scheduled and {performed} were performed ({pct}%).",
    },
    "fb_wait_by_triage": {"es": "Espera promedio en urgencias por nivel de triage:\n{lines}",
                          "en": "Average ER wait by triage level:\n{lines}"},
    "fb_specialty_demand": {"es": "Especialidades más solicitadas ({period}):\n{lines}",
                            "en": "Most requested specialties ({period}):\n{lines}"},
    # ---------- Alerts ----------
    "severity_critical": {"es": "CRÍTICA", "en": "CRITICAL"},
    "severity_high": {"es": "ALTA", "en": "HIGH"},
    "severity_medium": {"es": "MEDIA", "en": "MEDIUM"},
    "alert_occupancy": {
        "es": "{group}: ocupación estimada de {pct}% ({occupied}/{beds} camas), por encima del umbral de {threshold}%.",
        "en": "{group}: estimated occupancy {pct}% ({occupied}/{beds} beds), above the {threshold}% threshold.",
    },
    "alert_occupancy_action": {
        "es": "Recomendación: habilitar camas de expansión o trasladar pacientes estables a {target} "
              "({target_pct}% de ocupación) y reforzar el turno de enfermería.",
        "en": "Recommendation: open surge beds or move stable patients to {target} "
              "({target_pct}% occupied) and reinforce the nursing shift.",
    },
    "alert_occupancy_action_generic": {
        "es": "Recomendación: habilitar camas de expansión, acelerar altas pendientes y reforzar enfermería.",
        "en": "Recommendation: open surge beds, speed up pending discharges and reinforce nursing staff.",
    },
    "alert_inventory": {
        "es": "{name}: quedan {days} días de inventario (stock {stock}, consumo diario {daily}).",
        "en": "{name}: {days} days of inventory left (stock {stock}, daily use {daily}).",
    },
    "alert_inventory_action": {
        "es": "Recomendación: emitir orden de compra urgente por al menos {qty} unidades (cobertura de 15 días). "
              "Inventario simulado.",
        "en": "Recommendation: issue an urgent purchase order for at least {qty} units (15-day cover). "
              "Simulated inventory.",
    },
    "alert_er_wait": {
        "es": "La espera promedio en urgencias de los últimos 7 días es {mean} min (umbral {threshold} min).",
        "en": "The average ER wait over the last 7 days is {mean} min (threshold {threshold} min).",
    },
    "alert_er_wait_action": {
        "es": "Recomendación: reforzar médicos de urgencias en el turno de {shift}, donde la espera promedio es {shift_mean} min.",
        "en": "Recommendation: add ER physicians to the {shift} shift, where the average wait is {shift_mean} min.",
    },
    "alert_triage2": {
        "es": "Pacientes triage 2 esperan en promedio {mean} min en los últimos 7 días (meta: ≤ {threshold} min, Res. 5596/2015).",
        "en": "Triage 2 patients waited {mean} min on average over the last 7 days (target ≤ {threshold} min, Res. 5596/2015).",
    },
    "alert_triage2_action": {
        "es": "Recomendación: asignar un consultorio exclusivo para triage 2 en horas pico.",
        "en": "Recommendation: dedicate one consultation room to triage 2 at peak hours.",
    },
    "alert_surgery": {
        "es": "Solo el {pct}% de los procedimientos quirúrgicos programados en los últimos 30 días se realizaron "
              "({performed}/{scheduled}).",
        "en": "Only {pct}% of surgical procedures scheduled in the last 30 days were performed ({performed}/{scheduled}).",
    },
    "alert_surgery_action": {
        "es": "Recomendación: revisar causas de cancelación y reprogramar en las franjas con menor uso de quirófano.",
        "en": "Recommendation: review cancellation causes and reschedule into the lowest-use operating-room slots.",
    },
    "shift_day": {"es": "día", "en": "day"},
    "shift_night": {"es": "noche", "en": "night"},
    # ---------- Reports ----------
    "rep_wait_ci": {
        "es": "En los últimos {days} días la espera media en urgencias fue {mean} min. Con 95% de confianza, "
              "la media real está entre {low} y {high} min (n = {n}). La mediana es {median} min "
              "(IC 95% bootstrap {mlow}–{mhigh}); la distribución es asimétrica, por lo que la mediana "
              "representa mejor al paciente típico.",
        "en": "Over the last {days} days the mean ER wait was {mean} min. With 95% confidence the true mean "
              "lies between {low} and {high} min (n = {n}). The median is {median} min (95% bootstrap CI "
              "{mlow}–{mhigh}); the distribution is skewed, so the median better represents the typical patient.",
    },
    "rep_occupancy_ci": {
        "es": "{group}: ocupación diaria media {mean}% en los últimos {days} días (IC 95% {low}–{high}%). {verdict}",
        "en": "{group}: mean daily occupancy {mean}% over the last {days} days (95% CI {low}–{high}%). {verdict}",
    },
    "rep_occupancy_over": {
        "es": "Todo el intervalo supera el {threshold}%: la sobreocupación es sostenida, no un pico aislado.",
        "en": "The whole interval is above {threshold}%: over-occupancy is sustained, not a one-off peak.",
    },
    "rep_occupancy_under": {
        "es": "El intervalo está por debajo del {threshold}%: hay capacidad disponible de forma consistente.",
        "en": "The interval is below {threshold}%: capacity is consistently available.",
    },
    "rep_occupancy_mixed": {
        "es": "El intervalo cruza el {threshold}%: la ocupación oscila alrededor del umbral.",
        "en": "The interval crosses {threshold}%: occupancy oscillates around the threshold.",
    },
    "rep_compare": {
        "es": "Espera en urgencias: {current_label} mediana {cur_median} min (n = {n_cur}) vs. {previous_label} "
              "mediana {prev_median} min (n = {n_prev}). Prueba de Mann-Whitney U: {p}. {verdict}",
        "en": "ER wait: {current_label} median {cur_median} min (n = {n_cur}) vs. {previous_label} median "
              "{prev_median} min (n = {n_prev}). Mann-Whitney U test: {p}. {verdict}",
    },
    "rep_compare_sig_up": {
        "es": "La diferencia es estadísticamente significativa (α = 0,05): la espera AUMENTÓ ({effect}).",
        "en": "The difference is statistically significant (α = 0.05): waiting time INCREASED ({effect}).",
    },
    "rep_compare_sig_down": {
        "es": "La diferencia es estadísticamente significativa (α = 0,05): la espera DISMINUYÓ ({effect}).",
        "en": "The difference is statistically significant (α = 0.05): waiting time DECREASED ({effect}).",
    },
    "rep_compare_ns": {
        "es": "No hay evidencia suficiente de un cambio real (α = 0,05); la variación puede ser aleatoria.",
        "en": "There is not enough evidence of a real change (α = 0.05); the variation may be random.",
    },
    "rep_effect": {"es": "tamaño del efecto r = {r}, {size}", "en": "effect size r = {r}, {size}"},
    "effect_small": {"es": "pequeño", "en": "small"},
    "effect_medium": {"es": "moderado", "en": "moderate"},
    "effect_large": {"es": "grande", "en": "large"},
    "effect_negligible": {"es": "despreciable", "en": "negligible"},
    "rep_trend_up": {
        "es": "{subject}: tendencia creciente significativa en las últimas {weeks} semanas "
              "(+{slope} ingresos/semana, {p}, R² = {r2}). Se espera un aumento de ~{pct}% la próxima semana "
              "({forecast} ingresos). {action}",
        "en": "{subject}: significant upward trend over the last {weeks} weeks (+{slope} admissions/week, "
              "{p}, R² = {r2}). Expect ~{pct}% more next week ({forecast} admissions). {action}",
    },
    "rep_trend_down": {
        "es": "{subject}: tendencia decreciente significativa ({slope} ingresos/semana, {p}).",
        "en": "{subject}: significant downward trend ({slope} admissions/week, {p}).",
    },
    "rep_trend_none": {
        "es": "No se detectaron tendencias significativas (p < 0,05) en ingresos por diagnóstico ni por servicio.",
        "en": "No significant trends (p < 0.05) were detected in admissions by diagnosis or by service.",
    },
    "rep_root_shift": {
        "es": "Causa raíz — turno: la espera media es {day} min en el día y {night} min en la noche "
              "(Mann-Whitney {p}). {verdict}",
        "en": "Root cause — shift: mean wait is {day} min during the day and {night} min at night "
              "(Mann-Whitney {p}). {verdict}",
    },
    "rep_root_shift_sig": {
        "es": "El turno de {worse} concentra la demora de forma significativa.",
        "en": "The {worse} shift significantly concentrates the delay.",
    },
    "rep_root_shift_ns": {"es": "El turno no explica la demora.", "en": "The shift does not explain the delay."},
    "rep_root_triage": {
        "es": "Causa raíz — triage: Kruskal-Wallis {p}. El nivel con mayor espera es triage {level} "
              "({mean} min) y aporta el {share}% de los pacientes de urgencias del periodo.",
        "en": "Root cause — triage: Kruskal-Wallis {p}. The level with the longest wait is triage {level} "
              "({mean} min), accounting for {share}% of ER patients in the period.",
    },
    "rep_root_volume": {
        "es": "Causa raíz — volumen: la correlación de Spearman entre ingresos diarios a urgencias y espera media "
              "diaria es ρ = {rho} ({p}). {verdict}",
        "en": "Root cause — volume: Spearman correlation between daily ER admissions and daily mean wait is "
              "ρ = {rho} ({p}). {verdict}",
    },
    "rep_root_volume_sig": {
        "es": "A más pacientes, más espera: la demora está ligada a la demanda.",
        "en": "More patients means longer waits: the delay is demand-driven.",
    },
    "rep_root_volume_ns": {
        "es": "La demora no se explica solo por el volumen de pacientes.",
        "en": "The delay is not explained by patient volume alone.",
    },
    "rep_insufficient": {"es": "Datos insuficientes para este análisis.", "en": "Not enough data for this analysis."},
    "action_respiratory": {
        "es": "Recomendación: aumentar stock de antibióticos y broncodilatadores y reforzar terapia respiratoria.",
        "en": "Recommendation: increase antibiotic and bronchodilator stock and reinforce respiratory therapy.",
    },
    "action_injury": {
        "es": "Recomendación: reforzar ortopedia, quirófano de trauma e insumos de osteosíntesis.",
        "en": "Recommendation: reinforce orthopaedics, trauma OR slots and osteosynthesis supplies.",
    },
    "action_pregnancy": {
        "es": "Recomendación: prever camas de gineco-obstetricia y sala de partos.",
        "en": "Recommendation: plan obstetrics beds and delivery-room capacity.",
    },
    "action_infectious": {
        "es": "Recomendación: revisar stock de antimicrobianos y camas de aislamiento.",
        "en": "Recommendation: review antimicrobial stock and isolation beds.",
    },
    "action_generic": {
        "es": "Recomendación: ajustar camas y personal del servicio relacionado.",
        "en": "Recommendation: adjust beds and staff of the related service.",
    },
}

CHAPTER_LABELS: dict[str, dict[str, str]] = {
    "infectious": {"es": "Enfermedades infecciosas", "en": "Infectious diseases"},
    "neoplasms": {"es": "Tumores", "en": "Neoplasms"},
    "blood": {"es": "Enfermedades de la sangre", "en": "Blood diseases"},
    "endocrine": {"es": "Endocrinas y metabólicas", "en": "Endocrine and metabolic"},
    "mental": {"es": "Trastornos mentales", "en": "Mental disorders"},
    "nervous": {"es": "Sistema nervioso", "en": "Nervous system"},
    "eye": {"es": "Ojo", "en": "Eye"},
    "ear": {"es": "Oído", "en": "Ear"},
    "circulatory": {"es": "Sistema circulatorio", "en": "Circulatory system"},
    "respiratory": {"es": "Sistema respiratorio", "en": "Respiratory system"},
    "digestive": {"es": "Sistema digestivo", "en": "Digestive system"},
    "skin": {"es": "Piel", "en": "Skin"},
    "musculoskeletal": {"es": "Osteomuscular", "en": "Musculoskeletal"},
    "genitourinary": {"es": "Genitourinario", "en": "Genitourinary"},
    "pregnancy": {"es": "Embarazo, parto y puerperio", "en": "Pregnancy and childbirth"},
    "perinatal": {"es": "Perinatales", "en": "Perinatal conditions"},
    "congenital": {"es": "Congénitas", "en": "Congenital"},
    "symptoms": {"es": "Síntomas y signos", "en": "Symptoms and signs"},
    "injury": {"es": "Traumatismos y envenenamientos", "en": "Injuries and poisoning"},
    "external": {"es": "Causas externas", "en": "External causes"},
    "health_factors": {"es": "Factores de salud", "en": "Health factors"},
    "special": {"es": "Códigos especiales", "en": "Special codes"},
}


def lang_or_default(lang: str | None, default: str = "es") -> str:
    return lang if lang in SUPPORTED_LANGUAGES else default


def t(key: str, lang: str = "es", **params: Any) -> str:
    entry = MESSAGES.get(key)
    if not entry:
        return key
    template = entry.get(lang) or entry["es"]
    return template.format(**params) if params else template


def chapter_label(key: str | None, lang: str = "es") -> str:
    if not key:
        return "—"
    return CHAPTER_LABELS.get(key, {}).get(lang, key)


def fmt_number(value: Any, lang: str = "es", digits: int = 1) -> str:
    """1234.5 -> '1.234,5' (es) / '1,234.5' (en)."""
    if value is None:
        return "—"
    text = f"{float(value):,.{digits}f}" if digits else f"{int(round(float(value))):,}"
    if lang == "es":
        text = text.replace(",", "§").replace(".", ",").replace("§", ".")
    return text


def fmt_date(value: Any, lang: str = "es") -> str:
    import pandas as pd

    ts = pd.Timestamp(value)
    return ts.strftime("%d/%m/%Y") if lang == "es" else ts.strftime("%Y-%m-%d")
